version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 8
    separate-pull-requests: false
    allow:
      - dependency-name: '*'
    ignore:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
    commit-message:
      prefix: 'deps'
    versioning-strategy: auto
