api:
  - changed-files:
      - any-glob-to-any-file:
          - src/api/*
          - src/api/**/*
ui:
  - changed-files:
      - any-glob-to-any-file:
          - src/ui/*
          - src/ui/**/*
          - src/components/*
          - src/components/**/*
          - src/app/*
          - src/app/pages/**/*
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/*
          - tests/**/*
          - '**/*.spec.*'
          - '**/*.test.*'
infra:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*
          - .github/**/*
          - terraform/*
          - terraform/**/*
ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/workflows/**/*
styles:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*.css
          - src/**/*.scss
          - src/styles/*
          - src/styles/**/*
          - public/**/*.css
security:
  - changed-files:
      - any-glob-to-any-file:
          - SECURITY.md
          - security/*
          - security/**/*
          - .github/security/*
          - .github/security/**/*
chore:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - scripts/*
          - build/*
discussion:
  - changed-files:
      - any-glob-to-any-file:
          - discussions/*
typings:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*.d.ts
utility:
  - changed-files:
      - any-glob-to-any-file:
          - src/utils/*
          - src/helpers/*
