name: Mirror Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
      PROJECT_OWNER: ${{ secrets.PROJECT_OWNER }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add mirror https://${{ env.MIRROR_TOKEN }}@github.com/${{ env.PROJECT_OWNER }}/${{ env.PROJECT_NAME }}.git
          git push --mirror mirror