name: Mirror Project
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Mirror to User Repo
        run: |
          git fetch -p origin
          git push --mirror https://${{ secrets.MIRROR_TOKEN }}@github.com/${{ secrets.PROJECT_OWNER }}/${{ secrets.PROJECT_NAME }}.git
