name: Mirror Project # mirror to '2hoch1/dmw-project'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        # Step 1: Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v4 # Auf v4 aktualisieren
        with:
          fetch-depth: 0 # Vollständige History fetchen

        # Step 2: Push to the mirror repository
      - name: Push to mirror repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add mirror https://${{ secrets.MIRROR_TOKEN }}@github.com/2hoch1/dmw-project.git
          git push --mirror mirror