name: PR Title Linter

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: chore, build, ci, ui, api, docs, feat, fix, perf, refactor, revert, style, test, types
