name: Release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update package.json version
        run: |
          VERSION=${GITHUB_REF_NAME}
          npm version $VERSION --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore(release): update version to $VERSION"
          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main

      - name: Get previous tag
        id: prev_tag
        run: |
          git fetch --tags
          PREV_TAG=$(git tag --sort=-creatordate | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$' | grep -v "${GITHUB_REF_NAME}" | head -n 1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [ -n "${{ steps.prev_tag.outputs.prev_tag }}" ]; then
            git log --pretty=format:'- %s' ${{ steps.prev_tag.outputs.prev_tag }}..${GITHUB_REF_NAME} > release-notes.md
          else
            git log --pretty=format:'- %s' > release-notes.md
          fi

      - name: Check if pre-release
        id: prerelease
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ -(alpha|beta|rc) ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body_path: release-notes.md
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
