name: Update Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
